# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anonymizer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'anonymizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61nonymizer.proto\x12\x0epii_anonymizer\x1a\x1cgoogle/protobuf/struct.proto\"c\n\x06Policy\x12\x12\n\nentityType\x18\x01 \x01(\t\x12\x14\n\x0coperatorName\x18\x02 \x01(\t\x12/\n\x0eoperatorParams\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x7f\n\x16\x41nonymizeObjectRequest\x12\x12\n\nbucketName\x18\x01 \x01(\t\x12\x11\n\tobjectKey\x18\x02 \x01(\t\x12\x12\n\nobjectData\x18\x03 \x01(\x0c\x12*\n\npolicy_map\x18\x04 \x03(\x0b\x32\x16.pii_anonymizer.Policy\"J\n\x17\x41nonymizeObjectResponse\x12\x19\n\x11updatedObjectData\x18\x01 \x01(\x0c\x12\x14\n\x0cobjectLength\x18\x02 \x01(\x05\x32z\n\x14PIIAnonymizerService\x12\x62\n\x0f\x41nonymizeObject\x12&.pii_anonymizer.AnonymizeObjectRequest\x1a\'.pii_anonymizer.AnonymizeObjectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anonymizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POLICY']._serialized_start=66
  _globals['_POLICY']._serialized_end=165
  _globals['_ANONYMIZEOBJECTREQUEST']._serialized_start=167
  _globals['_ANONYMIZEOBJECTREQUEST']._serialized_end=294
  _globals['_ANONYMIZEOBJECTRESPONSE']._serialized_start=296
  _globals['_ANONYMIZEOBJECTRESPONSE']._serialized_end=370
  _globals['_PIIANONYMIZERSERVICE']._serialized_start=372
  _globals['_PIIANONYMIZERSERVICE']._serialized_end=494
# @@protoc_insertion_point(module_scope)
